name: chat_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase dependencies (compatible na Flutter 3.38)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^20.1.0

  # State management
  provider: 6.1.5
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

 